version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
  redis:
    image: 'redis:latest'
    deploy:
      mode: replicated
      replicas: 1
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: przet/zadanie2:nginx
    ports:
      - '3050:80'
    deploy:
      mode: replicated
      replicas: 1
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: przet/zadanie2:server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    image: przet/zadanie2:client
    volumes:
      - /app/node_modules
      - ./client:/app
    deploy:
      mode: replicated
      replicas: 1
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    image: przet/zadanie2:worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_OPTIONS=--openssl-legacy-provider
    deploy:
      mode: replicated
      replicas: 1
